name: Publish to npm

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm install

      - name: Check if version changed
        id: version_check
        run: |
          git fetch origin main --depth=2
          PREV_VERSION=$(git show HEAD~1:package.json | grep '"version"' | head -1)
          CURR_VERSION=$(cat package.json | grep '"version"' | head -1)
          echo "Previous: $PREV_VERSION"
          echo "Current: $CURR_VERSION"
          if [ "$PREV_VERSION" == "$CURR_VERSION" ]; then
            echo "No version change. Skipping publish."
            echo "publish=false" >> $GITHUB_OUTPUT
          else
            echo "publish=true" >> $GITHUB_OUTPUT
          fi

      - name: Publish to npm
        if: steps.version_check.outputs.publish == 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
